version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: ec2-deploy/scripts/before_install.sh
      timeout: 300

  AfterInstall:
    - location: ec2-deploy/scripts/after_install.sh
      timeout: 300

  ApplicationStart:
    - location: ec2-deploy/scripts/app_start.sh
      timeout: 300
